- hosts: terraform-ansible
  tasks:
  - name: Instalando o python3 e virtualenv
    apt:
      pkg:
      - python3
      - virtualenv
      update_cache: yes
    become: yes
  - name: Instalando depedencias com pip (Django e Django Rest)
    pip:
      virtualenv: /home/ubuntu/venv
      name:
        - django
        - djangorestframework
  - name: Cria um diretorio /home/ubuntu/python
    file:
      path: /home/ubuntu/python
      state: directory
      mode: '0755'
  - name: Verificando se o projeto já existe
    stat:
      path: /home/ubuntu/python/setup/settings.py
    register: projeto
  - name: Iniciando projeto
    shell: '. /home/ubuntu/venv/bin/activate; django-admin startproject setup /home/ubuntu/python'
    when: not projeto.stat.exists
  - name: Alterando o hosts do settings
    lineinfile:
      path: /home/ubuntu/python/setup/settings.py
      regexp: 'ALLOWED_HOSTS'
      line: 'ALLOWED_HOSTS = ["*"]'
      backrefs: yes